# -*- coding: utf-8 -*-
"""
Created on Fri Sep 27 13:02:16 2019

@author: jchlu
"""

 language: python
python:
  - "3.5"
install:
  - pip install requests
# command to run tests
script:
 - python -m unittest GithubAPI567
